# for test container

version: "3.8"
services:
  postgres:
    image: postgres:16.2
    container_name: postgres_test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"